app = "dzx-core"  # ou o nome do seu app no Fly

[build]
  image = "docker.all-hands.dev/all-hands-ai/openhands:0.46"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443