name: Deploy OpenHands no Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_KEY }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar PATH do Poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências do projeto
        run: poetry install --no-root

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Fazer login na Railway CLI
        run: echo "$RAILWAY_API_TOKEN" | railway login --ci

      - name: Linkar projeto e serviço Railway
        run: railway link --project prolific-curiosity --service dzx-core

      - name: Fazer deploy para o Railway
        run: railway up