jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}  # <-- Define o token aqui

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar PATH para Poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências com Poetry
        run: poetry install --no-root

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy no Railway
        run: railway up --yes