name: Deploy OpenHands no Railway (sem Docker)

on:
  push:
    branches:
      - main  # ajuste se usa outra branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_KEY }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Listar arquivos na raiz para debug
        run: ls -la

      - name: Listar arquivos dentro da pasta DZX-CORE para debug
        run: ls -la DZX-CORE || echo "Pasta DZX-CORE não existe"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar PATH para Poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências com Poetry
        run: poetry install --no-root

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy no Railway
        run: railway up