name: Deploy OpenHands no Railway (sem Docker)

on:
  push:
    branches:
      - main  # Altere para sua branch principal, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar PATH para Poetry
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências com Poetry
        run: poetry install --no-root

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Login Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy no Railway
        run: railway up --yes
