name: Deploy para Fly.io sem secrets de LLM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy para Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Espera o app iniciar
        run: sleep 10

      - name: Testa se o app responde
        run: |
          curl --fail --retry 5 https://dzx-core.fly.dev || (
            echo "App offline. Reiniciando..."
            fly restart --app dzx-core
          )
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Logs se falhar
        if: failure()
        run: fly logs --app dzx-core --max-lines 100
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}